package main

// Rendering a systemd unit and deciding whether a spec is allowed to become
// one. Deliberately free of any Linux-only call so the parts that decide what
// lands in /etc/systemd/system can be tested anywhere, including the Windows
// machine this is developed on. The filesystem and systemctl half lives in
// systemd_create_linux.go.

import (
	"fmt"
	"strings"

	"beacle/shared"
)

// validUnitName keeps the name to what systemd accepts and, more importantly,
// to something that cannot escape the unit directory. The name becomes a file
// path, so a slash or a .. here would be a write anywhere on the disk.
func validUnitName(name string) (string, error) {
	name = strings.TrimSpace(name)
	name = strings.TrimSuffix(name, ".service")
	if name == "" || len(name) > 64 {
		return "", fmt.Errorf("service name must be 1-64 characters")
	}
	for _, r := range name {
		ok := r == '-' || r == '_' || r == '.' || r == '@' ||
			(r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9')
		if !ok {
			return "", fmt.Errorf("service name may only contain letters, digits, dot, dash, underscore and @")
		}
	}
	if strings.HasPrefix(name, "-") || strings.HasPrefix(name, ".") {
		return "", fmt.Errorf("service name may not start with a dash or a dot")
	}
	return name, nil
}

// renderUnit turns a spec into a unit file. The panel never sends unit text —
// this is the only thing that decides what a Beacle-made unit looks like, so
// there is one place to audit and one place to fix.
func renderUnit(spec shared.SystemdUnitSpec) string {
	var b strings.Builder

	b.WriteString("# Generated by Beacle. Edits here are kept — Beacle only\n")
	b.WriteString("# rewrites this file when you save the service again.\n\n")

	b.WriteString("[Unit]\n")
	desc := strings.TrimSpace(spec.Description)
	if desc == "" {
		desc = spec.Name
	}
	fmt.Fprintf(&b, "Description=%s\n", oneLine(desc))
	after := strings.TrimSpace(spec.After)
	if after == "" {
		after = "network-online.target"
	}
	fmt.Fprintf(&b, "After=%s\n", oneLine(after))
	if strings.Contains(after, "network-online.target") {
		// After= alone does not pull the target in; without Wants= a service
		// that needs the network can start before there is one.
		b.WriteString("Wants=network-online.target\n")
	}
	// A service that keeps failing must not be parked in a failed state by the
	// restart rate limit: an agent-managed box is expected to keep trying.
	b.WriteString("StartLimitIntervalSec=0\n")

	b.WriteString("\n[Service]\n")
	b.WriteString("Type=simple\n")
	fmt.Fprintf(&b, "ExecStart=%s\n", oneLine(spec.ExecStart))
	if wd := strings.TrimSpace(spec.WorkingDir); wd != "" {
		fmt.Fprintf(&b, "WorkingDirectory=%s\n", oneLine(wd))
	}
	if u := strings.TrimSpace(spec.User); u != "" {
		fmt.Fprintf(&b, "User=%s\n", oneLine(u))
	}

	restart := spec.Restart
	switch restart {
	case "always", "on-failure", "no":
	default:
		restart = "always"
	}
	fmt.Fprintf(&b, "Restart=%s\n", restart)
	if restart != "no" {
		sec := spec.RestartSec
		if sec <= 0 {
			sec = 3
		}
		fmt.Fprintf(&b, "RestartSec=%d\n", sec)
	}

	// Sorted so saving the same service twice produces the same file, which is
	// what makes a diff mean something.
	//
	// Quoted because systemd splits Environment= on whitespace: an unquoted
	// value containing a space silently becomes a second variable named after
	// whatever followed the space.
	for _, k := range sortedKeys(spec.Env) {
		fmt.Fprintf(&b, "Environment=%s\n", quoteEnv(oneLine(k), oneLine(spec.Env[k])))
	}

	b.WriteString("\n[Install]\n")
	b.WriteString("WantedBy=multi-user.target\n")
	return b.String()
}

// quoteEnv renders one NAME="value" assignment, escaping what systemd treats
// as special inside a quoted string.
func quoteEnv(name, value string) string {
	v := strings.ReplaceAll(value, "\\", "\\\\")
	v = strings.ReplaceAll(v, "\"", "\\\"")
	return fmt.Sprintf("%s=\"%s\"", name, v)
}

// oneLine strips newlines. A newline in any of these values would let the
// caller append arbitrary directives — ExecStart of their choosing, running as
// root — so this is a boundary, not tidiness.
func oneLine(v string) string {
	v = strings.ReplaceAll(v, "\r", " ")
	v = strings.ReplaceAll(v, "\n", " ")
	return strings.TrimSpace(v)
}

// validateSpecFields checks everything that does not need the host — the
// filesystem checks are added by the caller on Linux.
func validateSpecFields(spec shared.SystemdUnitSpec) (string, error) {
	name, err := validUnitName(spec.Name)
	if err != nil {
		return "", err
	}
	if strings.TrimSpace(spec.ExecStart) == "" {
		return "", fmt.Errorf("command is required")
	}
	for k := range spec.Env {
		if strings.TrimSpace(k) == "" || strings.ContainsAny(k, "= 	") {
			return "", fmt.Errorf("environment name %q is invalid", k)
		}
	}
	return name, nil
}
